update jobs
Signed-off-by: mahjonp <junpeng.man@gmail.com>

diff --git a/jobs/bank_1.yaml b/jobs/bank_1.yaml
--- a/jobs/bank_1.yaml
+++ b/jobs/bank_1.yaml
@@ -1,10 +1,12 @@
+---
 apiVersion: batch/v1beta1
 kind: CronJob
 metadata:
   name: bank-1
   namespace: tipocket-job
 spec:
-  schedule: "0 */6 * * *"
+  schedule: "0 */4 * * *"
+  concurrencyPolicy: Forbid
   jobTemplate:
     spec:
       template:
@@ -13,15 +15,23 @@ spec:
           - name: tipocket
             image: pingcap/tipocket:latest
             command:
-              - /bin/chaos-tidb
-              - -case=bank
-              - -namespace=tipocket-test
-              - -image-version=v3.0.9
-              - -client=5
-              - -hub=hub.pingcap.net
-              - -nemesis=random_kill,partition_one,short_kill_tikv_1node,short_kill_pd_leader,kill_tikv_1node_5min
-              - -round=3
-              - -request-count=10000
+              - "sh"
+              - "-c"
+              - |
+                /bin/chaos-tidb \
+                -case=bank \
+                -namespace=tipocket-test \
+                -image-version=v3.0.9 \
+                -client=5 \
+                -hub=hub.pingcap.net \
+                -nemesis=random_kill,partition_one,short_kill_tikv_1node,short_kill_pd_leader,kill_tikv_1node_5min \
+                -round=3 \
+                -request-count=10000
+
+                if [ $? != "0" ]; then
+                  echo "ERROR OCCURED, PTAL..."
+                  while true; do sleep 60; done
+                fi
             env:
             - name: KUBECONFIG
               value: "/etc/config/kube_config"
